#!/usr/bin/python3
import sys
from sonic_platform.device_data import DeviceDataManager
from sonic_py_common.logger import Logger


logger = Logger(log_identifier='platform_wait')
logger.log_notice('Nvidia: Wait for SFP interfaces to be ready')
if DeviceDataManager.wait_modules_ready():
    logger.log_notice('Nvidia: SFP interfaces are ready')
    sys.exit(0)
else:
    logger.log_error('Nvidia: SFP interfaces are not ready: timeout')
    sys.exit(-1)
